version: '3'
services:
  zookeeper:
    hostname: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi:
    image: apache/nifi:1.9.2
    user: root
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./nifi:/config/
      - avro:/opt/nifi/nifi-current/avro
    entrypoint: >
      bash -c "cp /config/scripts/start.sh ./ && bash start.sh"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    depends_on: [zookeeper, db]

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: admin
      POSTGRES_DB: flow_results

  superset:
    image: amancevice/superset:0.34.0
    ports:
      - "8088:8088"
    user: root
    volumes:
      - ./superset:/etc/superset
    command: >
      bash -c "pip install psycopg2-binary
      && superset db upgrade
      && export FLASK_APP=superset
      && flask fab create-admin --username 'admin' --firstname Admin --lastname Admin --email noreply --password 'p@ssw0rd'
      && superset import_datasources -p /etc/superset/datasources.yaml
      && superset import_dashboards -p /etc/superset/dashboards.json
      && superset init
      && superset run -h 0.0.0.0 -p 8088"
    depends_on: [db]

volumes:
  avro:
    driver: local
