version: '3'
services:
  # nginx:
  #   image: nginx
  #   ports:
  #   - 80
  #   environment:
  #     - NGINX_HOST=localhost
  #     - NGINX_PORT=80
  #   command: >
  #     bash -c "apt update
  #     && apt install -y apache2-utils
  #     && htpasswd -cb /etc/nginx/.htpasswd admin 'p@ssw0rd'
  #     && exec nginx -g 'daemon off;"

  zookeeper:
    hostname: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi:
    image: apache/nifi:1.9.2
    ports:
      - "8080:8080"
    volumes:
      - ./nifi:/config/
    entrypoint: >
      bash -c "cp /config/scripts/start.sh ./ && bash start.sh"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    depends_on: [zookeeper, db]

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: admin
      POSTGRES_DB: flow_results

  superset:
    image: amancevice/superset:0.28.1
    ports:
      - "8088:8088"
    volumes:
      - ./superset:/etc/superset
    command: >
      bash -c "
      fabmanager create-admin --app superset --username 'admin' --firstname Admin --lastname Admin --email noreply --password 'p@ssw0rd'
      && superset db upgrade
      && superset import_datasources -p /etc/superset/datasources.yaml
      && superset import_dashboards -p /etc/superset/dashboards.json
      && superset init
      && superset runserver -d"
    depends_on: [db]
